### ISSUE TITLE
ZMQ error when try to run an exsample model

### ISSUE THREAD

**Issue by ghost** [DavoudTaghawiNejad/abce#2]
Hi,

I'm really interested with the project as an macroeconomist with skepticism to DSGE and python familiality. Instralltion seems suceeded into my "anaconda" on windows envroment. But, I've just an error when I tried to run example model "...\example\2sectors\start.py " .  The error message is like below. It would be really helpful if you look at this and hint some solutions when you have time. 

Best regards,

###########################################
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\Anaconda\lib\multiprocessing\forking.py", line 495, in prepa
re
    '__parents_main__', file, path_name, etc
  File "M:\Takashi SHIONO\Numerical\ABCE\example\2sectors\start.py", line 11, in
 <module>
    w = Simulation(simulation_parameters)
  File "C:\Python27\Anaconda\lib\site-packages\abce\__init__.py", line 225, in _
_init__
    self.commands.bind(self._addresses['command_addresse'])
  File "socket.pyx", line 448, in zmq.backend.cython.socket.Socket.bind (zmq\bac
kend\cython\socket.c:4126)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq\back
end\cython\socket.c:6174)
zmq.error.ZMQError: Address in use

**Comment by DavoudTaghawiNejad** [comment]
ZMQ has been removed and multiprocessing is achieved without the use of external libraries. ABCE 0.5 has been largely rewritten and is released as an alpha release.
